### PR TITLE
Add ConfigureAspNetCoreDefaults

### PR DESCRIPTION
**Pull request by HaoK**
Initial prototype of https://github.com/aspnet/MetaPackages/issues/117

- New ConfigureAspNetCoreDefaults() that will add all of the IConfigureOptions for the default sections
- Currently: Kestral/OIDC/Google/Facebook/Twitter/MSA/JwtBearer/Identity
- Moved kestrel config under Microsoft:AspNetCore:Hosting

### CODE REVIEW

**Review by Eilon — CHANGES_REQUESTED** [review]
cc @davidfowl @DamianEdwards 

We need to think a bit more about which dependencies go where. We can't add too many deps to the mini-metapackage. But, if we add this to the All-metapackage, then it can't be used from .NET Framework apps/templates.

**Comment by HaoK** [comment]
Updated using new options infrastructure.  Should the kestrel setup move to Kestrel instead of living here like the rest of the default setup?

**Comment by HaoK** [comment]
@JunTaoLuo do you own MetaPackage?  Who should review this change?

**Comment by HaoK** [comment]
Merged without the kestrel changes which would break templates without the corresponding config update

**Pull request closed without merging**
