### PR TITLE
Produce tar.gz file for osx and linux package store

### LINKED ISSUE #48: Produce Linux package store as a tarball instead of zip
Our docker images don't have `unzip` installed. If we produce a tarball instead, then we can use `tar` to extract the package cache.

cc @JunTaoLuo

### PR DESCRIPTION
**Pull request by natemcmaster**
Resolves #48 

Required for https://github.com/aspnet/aspnet-docker/issues/215

### CODE REVIEW

**Comment by JunTaoLuo** [comment]
gah this is going to conflict with #67

**Comment by muratg** [comment]
@natemcmaster @JunTaoLuo Do we need to sit down and talk about how the folder structure look like across different archives and installers?

**Comment by natemcmaster** [comment]
I trust @JunTaoLuo knows these details. I'm not familiar with folder structure expectations. This change is simply about converting a .zip to a .tar.gz so Docker install is possible.

**Comment by JunTaoLuo** [comment]
I don't see why the folder structure would need to be different on different archives? Why do we have this concern? Also, this PR needs to be rebased but looks correct

**Pull request closed without merging**
