### PR TITLE
Wire up the IncludeScopes configuration option, closes #204

### LINKED ISSUE #204: IncludeScopes in config doesn't work in the template
See:
https://github.com/aspnet/Logging/issues/643

Please fix before RTM

### PR DESCRIPTION
**Pull request by NinoFloris**
This option should affect the ConsoleLogger and isn't today

### CODE REVIEW

**Comment by Eilon** [comment]
@muratg - who should review this?

**Comment by muratg** [comment]
Assigning to @JunTaoLuo for review.

**Comment by JunTaoLuo** [comment]
This looks odd. We pass in the configuration to the `ILoggerBuilder` but it does not flow the `IncludeScopes` configuration to the `ConsoleLogger`. I feel that the configuration of our loggers needs an update instead of this change. cc @BrennanConroy @pakrym thoughts?

**Comment by pakrym** [comment]
This is caused by bigger issue and this is not the right solution.

Issue is that we need a general way to wire logger providers `ConfigureOptions` to `IConfiguration` instances assigned to logging configuration.

**Comment by pakrym** [comment]
Filed: https://github.com/aspnet/Logging/issues/688

**Comment by NinoFloris** [comment]
Cool don't mind how it's fixed, saw that you already had some issues open around flowing IncludeScopes config. When filed I hoped this quick fix could still make RTM but alas. 
Thanks for picking it up

**Pull request closed without merging**
